
package cn.cbirc.webservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "PolicyInterpretationWebServiceImplService", targetNamespace = "http://webservice.cbirc.cn", wsdlLocation = "http://localhost:8002/services/ws/api?wsdl")
public class PolicyInterpretationWebServiceImplService
    extends Service
{

    private final static URL POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_QNAME = new QName("http://webservice.cbirc.cn", "PolicyInterpretationWebServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:8002/services/ws/api?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public PolicyInterpretationWebServiceImplService() {
        super(__getWsdlLocation(), POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_QNAME);
    }

    public PolicyInterpretationWebServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public PolicyInterpretationWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_QNAME);
    }

    public PolicyInterpretationWebServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_QNAME, features);
    }

    public PolicyInterpretationWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public PolicyInterpretationWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns PolicyInterpretationService
     */
    @WebEndpoint(name = "PolicyInterpretationWebServiceImplPort")
    public PolicyInterpretationService getPolicyInterpretationWebServiceImplPort() {
        return super.getPort(new QName("http://webservice.cbirc.cn", "PolicyInterpretationWebServiceImplPort"), PolicyInterpretationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns PolicyInterpretationService
     */
    @WebEndpoint(name = "PolicyInterpretationWebServiceImplPort")
    public PolicyInterpretationService getPolicyInterpretationWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservice.cbirc.cn", "PolicyInterpretationWebServiceImplPort"), PolicyInterpretationService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_EXCEPTION;
        }
        return POLICYINTERPRETATIONWEBSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
