
package cn.cbirc.webservice;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "PolicyInterpretationService", targetNamespace = "http://webservice.cbirc.cn")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface PolicyInterpretationService {


    /**
     * 
     * @param docIdentifier
     * @param docTitle
     * @param startTime
     * @param endTime
     * @param docDepart
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "count", targetNamespace = "http://webservice.cbirc.cn", className = "cn.cbirc.webservice.Count")
    @ResponseWrapper(localName = "countResponse", targetNamespace = "http://webservice.cbirc.cn", className = "cn.cbirc.webservice.CountResponse")
    public int count(
        @WebParam(name = "docTitle", targetNamespace = "")
        String docTitle,
        @WebParam(name = "docIdentifier", targetNamespace = "")
        String docIdentifier,
        @WebParam(name = "docDepart", targetNamespace = "")
        String docDepart,
        @WebParam(name = "startTime", targetNamespace = "")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        String endTime);

    /**
     * 
     * @param id
     * @return
     *     returns cn.cbirc.webservice.PolicyInterpretationVO
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getById", targetNamespace = "http://webservice.cbirc.cn", className = "cn.cbirc.webservice.GetById")
    @ResponseWrapper(localName = "getByIdResponse", targetNamespace = "http://webservice.cbirc.cn", className = "cn.cbirc.webservice.GetByIdResponse")
    public PolicyInterpretationVO getById(
        @WebParam(name = "id", targetNamespace = "")
        int id);

    /**
     * 
     * @param docIdentifier
     * @param pageNo
     * @param pageSize
     * @param docTitle
     * @param startTime
     * @param endTime
     * @param withBody
     * @param docDepart
     * @return
     *     returns java.util.List<cn.cbirc.webservice.PolicyInterpretationVO>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "list", targetNamespace = "http://webservice.cbirc.cn", className = "cn.cbirc.webservice.List")
    @ResponseWrapper(localName = "listResponse", targetNamespace = "http://webservice.cbirc.cn", className = "cn.cbirc.webservice.ListResponse")
    public List<PolicyInterpretationVO> list(
        @WebParam(name = "withBody", targetNamespace = "")
        boolean withBody,
        @WebParam(name = "docTitle", targetNamespace = "")
        String docTitle,
        @WebParam(name = "docIdentifier", targetNamespace = "")
        String docIdentifier,
        @WebParam(name = "docDepart", targetNamespace = "")
        String docDepart,
        @WebParam(name = "startTime", targetNamespace = "")
        String startTime,
        @WebParam(name = "endTime", targetNamespace = "")
        String endTime,
        @WebParam(name = "pageNo", targetNamespace = "")
        int pageNo,
        @WebParam(name = "pageSize", targetNamespace = "")
        int pageSize);

}
